### ISSUE TITLE
Working with unloaded classes

### ISSUE THREAD

**Issue by Jason-purse** [diguage/byte-buddy-tutorial#19]
感谢您的issue,让我看到官网作者已经给出具体的做法,您示例中给出的做法,在我的测试中等价于加载了一个新的class(而原始的Bar没有任何变化),我并不了解byte buddy,我认为它可能类加载策略(导致它向引导类加载器 反射注入了类 ,这是默认行为,否则Wrapper 策略会创建一个新的类加载器进行类加载),而不等价于 系统类加载器中的Bar类

![image](https://user-images.githubusercontent.com/57804598/183845861-83c3d49d-4f2d-457f-95da-c417c0b9b574.png)

也就是说应该使用反射替换到系统类加载器的加载类 ..
这是我的见解 ...

**Comment by diguage** [comment]
不客气，欢迎以后多交流。一起学习。
这个问题，我还没搞清楚，我还要再做一下实验，确认一下
